# Change these first
owner: dani-Devofficial # Your GitHub organization or username, where this repository lives
repo: DaniLabStatus # The name of this repository

sites:
  - name: DaniLab Homepage
    url: https://dani.ggm.kr
    interval: 5
  - name: Sayknow Homepage
    url: https://sayknow.ggm.kr
    interval: 5
  - name: Sayknow Count Server
    url: https://vqtolrqlqvfpzjsedjrw.supabase.co/functions/v1/smooth-task/?askdata=hallo
    interval: 30
    expectedStatusCodes: [200, 201, 400, 429]
  - name: HuggingFace Sayknow
    url: https://sayknowlab-sayknow-v1.hf.space
    interval: 30
  - name: Status Page
    url: https://status.dani.ggm.kr/
    interval: 5

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.dani.ggm.kr
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: DaniLab Status
  introTitle: "**DaniLab** 상태 페이지입니다. 서버 없이 Github actions로 작동됩니다."
  introMessage: "This is the **DaniLab** status page. It runs on GitHub Actions without a server."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
